spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  data:
    neo4j:
      uri: neo4j://localhost:7687
      password: password
      username: neo4j
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
logging:
  level:
    org:
      neo4j:
        ogm:
          drivers:
            bolt:
              request:
                BoltRequest: DEBUG
