spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  data:
    neo4j:
      database: twitter
  neo4j:
    uri: bolt://demo.neo4jlabs.com:7687
    authentication:
      password: twitter
      username: twitter
    security:
      encrypted: true
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
logging:
  level:
    org:
      neo4j:
        ogm:
          drivers:
            bolt:
              request:
                BoltRequest: DEBUG

#org:
#  neo4j:
#    driver:
#      uri: bolt://demo.neo4jlabs.com:7687
#      authentication:
#        username: twitter
#        password: twitter
#      config :
#        encrypted : true
#database: twitter

